// export * from './alert/Alert';
// export * from './avatar/Avatar';
export * from './buttons';
// export * from './cards';
// export * from './divider/Divider';
// export * from './inputs';
// export * from './inputs/date-picker/DatePicker';
// export * from './inputs/switch/Switch';
// export * from './pagination/Pagination';
// export * from './pagination/variants/SimplePagination';
// export * from './steps/Steps';
// export * from './table/Table';
// export * from './tabs/Tabs';
// export * from './tag/Tag';
// export * from './tooltip/Tooltip';
// export * from './tour-tooltip-card/TourTooltipCard';
// export * from './typography';
// export * from './upload/Upload';
// export * from './upload/variants/CustomUpload';
// export * from './upload/variants/DraggerUpload';
export * from './test-component/TestComponent'
